In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv('Ames_Housing_Data_Final.csv')

In [10]:
df.head()

,Unnamed: 0,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
0,0,141.0,31770,6,5,1960,1960,112.0,639.0,0.0,...,0,0,0,0,1,0,0,0,1,0
1,1,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,0,0,0,0,1,0,0,0,1,0
2,2,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,0,0,0,0,1,0,0,0,1,0
3,3,93.0,11160,7,5,1968,1968,0.0,1065.0,0.0,...,0,0,0,0,1,0,0,0,1,0
4,4,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,0,0,0,0,1,0,0,0,1,0

In [12]:
df = df.drop('Unnamed: 0', axis = 1)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2925 entries, 0 to 2924
Columns: 274 entries, Lot Frontage to Sale Condition_Partial
dtypes: float64(11), int64(263)
memory usage: 6.1 MB

In [14]:
df.describe()

,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,...,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
count,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,...,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000
mean,69.683099,10109.861538,6.091624,5.563761,1971.323761,1984.229060,100.318632,438.974359,49.790427,558.959316,...,0.002735,0.080684,0.002393,0.000342,0.866325,0.004103,0.007863,0.015726,0.824615,0.082735
std,21.344161,7785.509739,1.406386,1.112262,30.228826,20.857822,176.667803,439.426274,169.274143,439.729905,...,0.052235,0.272395,0.048870,0.018490,0.340361,0.063931,0.088341,0.124437,0.380361,0.275528
min,0.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,60.000000,7438.000000,5.000000,5.000000,1954.000000,1965.000000,0.000000,0.000000,0.000000,218.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,70.000000,9430.000000,6.000000,5.000000,1973.000000,1993.000000,0.000000,370.000000,0.000000,465.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,80.000000,11526.000000,7.000000,6.000000,2000.000000,2004.000000,162.000000,734.000000,0.000000,801.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,2288.000000,1526.000000,2336.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [15]:
X = df.drop('SalePrice', axis = 1)
y = df['SalePrice']

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1, random_state=101)

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
scaler = StandardScaler()

In [20]:
scaler.fit(X_train)

StandardScaler()

In [36]:
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [28]:
from sklearn.model_selection import GridSearchCV

In [38]:
from sklearn.linear_model import ElasticNet

In [39]:
elastic_net_model = ElasticNet()

In [41]:
e_param = {
    'alpha': [0.1,1,5,10,50,100],
    'l1_ratio': [.1, .5 , .7 , .9 , .95 , .99 , 1]
}

In [46]:
grid_elastic_net = GridSearchCV(estimator = elastic_net_model,param_grid=e_param, scoring = 'neg_mean_squared_error', cv = 5, verbose=1)

In [47]:
import warnings
warnings.filterwarnings('ignore')
grid_elastic_net.fit(scaled_X_train, y_train)

Fitting 5 folds for each of 42 candidates, totalling 210 fits

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [0.1, 1, 5, 10, 50, 100],
                         'l1_ratio': [0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]},
             scoring='neg_mean_squared_error', verbose=1)

In [48]:
grid_elastic_net.best_params_

{'alpha': 100, 'l1_ratio': 1}

In [53]:
predictions = grid_elastic_net.predict(scaled_X_test)

In [54]:
predictions

array([115030.0108828 , 330700.15372654, 201207.12731429, 196378.72400031,
       102219.74319082, 149001.41833178, 130072.86469072, 344190.99699698,
        86317.81211648, 214611.83988343, 280702.74310865, 133181.46547467,
       313228.76346267, 110025.52409208, 162260.28149297, 235688.91560529,
       212164.9071257 , 139729.23537012, 166151.3842688 , 138201.59345812,
       163063.02559551, 217573.52020481, 252731.55626605, 225696.62317213,
       143089.79702881, 180148.28076638, 126670.91277983, 259872.59348454,
       186330.54115183, 217235.54894129,  72441.18646171, 117379.48599897,
       153390.9769354 , 191146.92308306, 247299.30063386,  90128.32765601,
        91978.63317599, 135154.72698894, 212033.10745544, 211636.19384069,
       165084.76510891, 269665.98189404, 196236.07683552, 157678.75420519,
       169504.22735377, 291698.85706455, 108640.38433264, 106942.01149915,
       407661.01966128, 238562.39217868, 143419.85167273, 199431.46443486,
       228893.12046043, 384174.28809824, 306154.26578505, 225691.31007521,
       266565.05488367, 188493.31759649, 109543.94076354, 208259.11886153,
       118240.51645211, 132879.46521953, 224916.46564256, 128077.59732774,
       157453.86994696, 225485.64713422, 121365.18128102, 185185.52790182,
       127750.39391529, 128051.64617353, 445856.64049201, 172748.69114312,
       223378.37616676, 146454.09083017, 205525.03106692, 289540.32565318,
       473146.9417126 , 157073.53690929, 255172.72060492, 229646.90409844,
       114146.42267231, 210569.9555209 , 141588.37183861, 327696.75574218,
       191494.38163571, 137801.12604784, 146005.47058688, 151661.92812058,
       117541.29978648, 275275.26015349, 145734.13872734, 231031.74760269,
       204461.33219624, 411840.27496706, 221437.85494027, 124792.30397283,
       162529.81296581, 251878.74537716, 114476.69671652, 146515.88983253,
       204666.67190795, 187593.73535747, 134626.84717114, 206933.29188627,
       171361.54019444,  88289.36969054,  77290.74552602, 143166.34985435,
       184175.26412745, 118331.07618825, 114987.3302115 , 181039.41455181,
       100508.56429739, 118121.38595135, 186731.15046299, 247024.28509083,
       293113.72779972, 165472.87442442, 127791.90102219, 151743.94095747,
       197076.16245365, 247289.34751171, 295057.82903147, 172782.11331111,
       149773.93315752, 103214.88524052, 307998.69783674, 229524.65266516,
       149796.94363652, 254519.25153979, 207881.16342069, 179123.73078909,
       139551.23191933, 143020.21539047, 171513.73703748, 318095.31974666,
       193968.87376068, 136322.83201361, 261246.47808516, 127214.92856645,
       230931.46100948, 189641.33182253, 188004.77706996, 110789.58451922,
       150977.08754615, 165578.96529472, 370826.36482335, 192482.22707649,
       237196.68542604, 214552.31988937, 148916.74828528, 213401.77970121,
       256873.49130123, 257818.12467761, 295246.23470582, 124678.16968355,
       295742.73601047, 183833.80014867, 120887.80011894, 115974.25044867,
        76078.49990743, 245513.52662191,  98209.4339788 ,  33162.02993658,
       191965.7407549 , 190235.67451181, 178210.62282352, 323851.04415188,
       160742.06580614, 181353.3931714 , 340429.98497472, 164018.53361519,
       133836.63370239, 201443.51912294, 141883.91008881, 135088.19617628,
       130886.34173033, 205426.39028252, 105789.14953732, 300147.82342855,
       204768.24839205, 149322.16733858, 138240.11170388, 288825.69048827,
       148044.05121816, 127441.73959039, 107668.0456531 , 134910.41206199,
       194607.83302068, 145329.34874582, 173215.72517046, 186026.04938939,
       127777.9054624 , 234581.54792859, 256381.89601679, 183197.60071968,
       122086.36582327, 183466.21168183, 178397.76322197, 259166.49557201,
       207026.42275896, 222836.11256431, 173018.7240865 ,  92703.34183953,
       222027.42829695, 207392.50304015, 231292.54495636, 235604.44732673,
       187897.71808187,  80824.03724275, 112098.58832854,  91299.00723462,
        97624.56758067, 205760.32790569, 126890.11806531, 141648.84249688,
       273154.27190397,  72366.47332102, 218958.45051227, 138761.46963742,
       125966.00947022, 220116.6058477 , 143958.96221146, 126830.14850188,
        84933.22050039, 171647.95514053, 165618.84365421, 143897.20389092,
       214654.65391284, 158318.46644433, 290393.02959031,  80832.02894333,
       154686.69929887, 114916.9359472 , 103885.2570439 , 156885.88223499,
       221180.18259749,  93352.62998041, 222099.3483058 , 351650.22312063,
       172363.88864039, 119341.33558298, 170586.87418671, 384010.82212395,
       127165.57741951, 137633.38945975, 156519.37815274, 162494.105601  ,
       142550.66536849, 182446.55184828, 257506.1522129 , 215855.83697139,
       222543.50510097, 217783.21245511, 162372.23032314, 127848.55700053,
       126458.10045631, 149918.58386861, 134918.64964791, 157148.01303162,
       136849.93654192,  96755.04987117, 207846.89024757, 103403.15233259,
       111315.4169329 , 187965.33422142, 172302.72528368, 124235.75291108,
       182186.20403136,  96958.18312115, 276319.74776266, 121051.06497675,
       384309.97055782, 208746.18808577, 119848.17298893, 124712.97220244,
       189689.21866408, 116793.70427013,  93868.98986488, 340839.62092379,
       167293.7881319 , 177638.10875165, 221737.39130783, 157968.9749088 ,
       234497.44194489, 124227.38396354, 169796.47961232, 288642.21270182,
       136881.98087181, 141489.77979297, 283482.35042987, 335152.68294515,
       226587.34179686])

In [55]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [56]:
MAE = mean_absolute_error(y_test , predictions)
MAE

14195.354900562173

In [58]:
RMSE = np.sqrt(mean_squared_error(y_test, predictions))
RMSE

20558.508566893157